### ISSUE TITLE
局部注册 import VueTree from 'vue-simple-tree/src/components/Vue-tree.vue' 报找不到

### ISSUE THREAD

**Issue by Mrlonglong** [jiaxincui/vue-tree#2]
Module not found: Error: Can't resolve 'vue-simple-tree/src/components/Vue-tree.vue'

**Comment by jiaxincui** [comment]
2.0版本进行了重构，引用路径为`vue-simple-tree/src/components/VueTree.vue`，感谢提醒，稍后更新README
