### ISSUE TITLE
item-click返回节点信息 不只是id

### ISSUE THREAD

**Issue by linxing58** [jiaxincui/vue-tree#4]
我的需求是弹框选择树节点，但item-click返回的是id，需要显示name信息，从treedata里边过滤效率有些低
            addAChild(id){
                this.$emit('add-a-child', id)
            },
            itemClick(id){
                this.$emit('item-click', id)
            },
            itemEdit(id) {
                this.$emit('item-edit', id)
            },
            itemDelete(id) {
                this.$emit('item-delete', id)
            }
参数id改为model

**Comment by jiaxincui** [comment]
目前，只能绑定 ids 后续版本会考虑绑定 `model` 或包含更多信息
